spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tweet
    username: humber
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true